scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params: 
    box_frame: base_link
    min_x: -0.27
    max_x: 0.27
    min_y: -0.2
    max_y: 0.2
    min_z: -0.115
    max_z: 0